### ISSUE TITLE
[Feature Request]: RISC-V BCJ filter

### ISSUE THREAD

**Issue by ivq** [tukaani-project/xz-embedded#1]
### Describe the Feature

Thank you for your outstanding work on the project and for completing the RISC-V filter recently! 
However, the RISC-V filter is missing in this repo, xz-embedded.
It would be great to integrate the filter. Is there any plan to do so? I am willing to help.

### Will I try to implement this new feature?

No

**Comment by Larhzu** [comment]
It will certainly be there. There just are a few other XZ-related things going on too so I don't know right now if it will get done this month, sorry.

**Comment by Larhzu** [comment]
I got a preliminary version done locally. It may take a few days until it's in the Git repository but it shouldn't take too many days. It likely won't be in Linux 6.9 but hopefully 6.10 is doable. We'll see.

**Comment by Larhzu** [comment]
It's in the master branch now under the 0BSD license. It was [submitted to Linux](https://lore.kernel.org/lkml/20240320183846.19475-1-lasse.collin@tukaani.org/T/#m6420529145b5f53f4e56060b7d9fa4f353717257) too.

Note the changes to xz_wrap.sh in the master branch or in the linked Linux patchset. Those alignment tweaks are an easy way to get a small extra improvement in compression.
